name: CI
on:
  schedule:
    - cron: "22 4 * * *"
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-container:
    name: "Build container image"
    uses: curium-rocks/flows/.github/workflows/oci-build-image.yml@main
    with:
      registry: ghcr.io/bryopsida
      image_name: protonmail-bridge
      push_in_pr: true